apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-1
          mountPath: /usr/share/nginx/html/ 
      volumes:
      - name: nginx-1
        configMap:
          name: configmap-app-one
---
apiVersion: v1
kind: Service
metadata:
  name: service-app-one
spec:
  selector:
    app: app-one 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


