apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-content
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: apache-content
        configMap:
          name: configmap_app1
---
apiVersion: v1
kind: Service
metadata:
  name: service_app1
spec:
  selector:
    app: app1 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

