apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-2
          mountPath: /usr/share/nginx/html/ 
      volumes:
      - name: nginx-2
        configMap:
          name: configmap-app-two
---
apiVersion: v1
kind: Service
metadata:
  name:  service-app-two
spec:
  selector:
    app: app-two
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
