apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app1-html
          mountPath: /usr/share/nginx/html/index.html
        - name: app1-conf
          mountPath: /etc/nginx/conf.d/default.conf
      volumes:
      - name: app1-html
        hostPath:
          path: /vagrant/app1/index.html
      - name: app1-conf
        hostPath:
          path: /vagrant/app1/default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  selector:
    app: app-one
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # ingressClassName: nginx
  rules:
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-one
            port:
              number: 80
