
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"

  config.vm.define "sriyaniS" do |control|
    control.vm.hostname = "sriyaniS"
    control.vm.network "private_network", ip:"192.168.56.110"
    control.vm.synced_folder ".", "/vagrant"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "sriyaniS"]
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
      end
  end
  config.vm.provision "shell", inline: <<-SHELL
    cp -r /vagrant/apps /vagrant/conf /vagrant/ingress.yaml .
  SHELL
  config.vm.provision "shell", path: "./scripts/server_script.sh"
end