Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define("aelasriS") do |aelasriS|
    aelasriS.vm.hostname = "aelasriS"
    aelasriS.vm.network "private_network", ip: "192.168.56.110"
    aelasriS.vm.provision "shell", path: "./k3s_controller.sh"

    aelasriS.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "4096"
    end
  end

  config.vm.define("aelasriSW") do |aelasriSW|
    aelasriSW.vm.hostname = "aelasriSW"
    aelasriSW.vm.network "private_network", ip: "192.168.56.111"
    aelasriSW.vm.provision "shell", path: "./k3s_agent.sh"

    aelasriSW.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "4096"
    end
  end
end