apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: apache-content
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: apache-content
        configMap:
          name: configmap_app3
---
apiVersion: v1
kind: Service
metadata:
  name: service_app3
spec:
  selector:
    app: app3
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP

