apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-three
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app3-html
          mountPath: /usr/share/nginx/html/index.html
        - name: app3-conf
          mountPath: /etc/nginx/conf.d/default.conf
      volumes:
      - name: app3-html
        hostPath:
          path: /vagrant/app3/index.html
      - name: app3-conf
        hostPath:
          path: /vagrant/app3/default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  selector:
    app: app-three
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # ingressClassName: nginx
  rules:
  # - host: app3.com
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-three
            port:
              number: 80
