apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app1-html
          mountPath: /usr/share/nginx/html/index.html
        - name: app1-conf
          mountPath: /etc/nginx/conf.d/default.conf
            #subPath: default.conf
      volumes:
      - name: app1-html
        hostPath:
          path: /vagrant/apps/configure/app1/index.html
      - name: app1-conf
        hostPath:
          path: /vagrant/apps/configure/app1/default.conf

