apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app3-html
          mountPath: /usr/share/nginx/html
        - name: app3-conf
          mountPath: /etc/nginx/conf.d/default.conf
          #subPath: default.conf
      volumes:
      - name: app3-html
        hostPath:
          path: /vagrant/apps/configure/app3
      - name: app3-conf
        hostPath:
          path: /vagrant/apps/configure/app3/default.conf
